version: "2"

services:
  node_app:
    build: ./web/nodeApp
    volumes:
      - ./web/assets_one:/usr/src/app/web/static
      - ./web/assets_two:/usr/src/app/web/static
    ports:
      - "3000:3000"
    command: "npm run serve"
